
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epzwazefpgnjjkystnan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwendhemVmcGduampreXN0bmFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzOTc3NDYsImV4cCI6MjA1Njk3Mzc0Nn0.FeCgxmwinu3sV6lOftlUQUFzN5rKnxtrNiAm0DXEaQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Define the custom database type with our new tables
export type CustomDatabase = Database & {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          name: string | null;
          email: string;
          phone: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          birth_date: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name?: string | null;
          email: string;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          birth_date?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string | null;
          email?: string;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          birth_date?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          type: 'info' | 'success' | 'warning' | 'error';
          read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          message: string;
          type: 'info' | 'success' | 'warning' | 'error';
          read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          type?: 'info' | 'success' | 'warning' | 'error';
          read?: boolean;
          created_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          regular_price: number;
          sale_price: number | null;
          promotional_price: number | null;
          rental_price: number | null;
          is_rental: boolean | null;
          material: string | null;
          size_info: string | null;
          care_instructions: string | null;
          created_at: string;
          updated_at: string;
          width: number | null;
          height: number | null;
          depth: number | null;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          regular_price: number;
          sale_price?: number | null;
          promotional_price?: number | null;
          rental_price?: number | null;
          is_rental?: boolean | null;
          material?: string | null;
          size_info?: string | null;
          care_instructions?: string | null;
          created_at?: string;
          updated_at?: string;
          width?: number | null;
          height?: number | null;
          depth?: number | null;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          regular_price?: number;
          sale_price?: number | null;
          promotional_price?: number | null;
          rental_price?: number | null;
          is_rental?: boolean | null;
          material?: string | null;
          size_info?: string | null;
          care_instructions?: string | null;
          created_at?: string;
          updated_at?: string;
          width?: number | null;
          height?: number | null;
          depth?: number | null;
        };
      };
      maternity_photoshoots: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          instagram_handle: string | null;
          image_url: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          instagram_handle?: string | null;
          image_url: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          instagram_handle?: string | null;
          image_url?: string;
          created_at?: string;
        };
      };
    } & Database['public']['Tables'];
  };
};

// Use our custom database type with the createClient
export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
