// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epzwazefpgnjjkystnan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwendhemVmcGduampreXN0bmFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzOTc3NDYsImV4cCI6MjA1Njk3Mzc0Nn0.FeCgxmwinu3sV6lOftlUQUFzN5rKnxtrNiAm0DXEaQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);